export interface Assignment {
  id: string;
  title: string;
  course: string; 
  deadline: string; // e.g., "2024-03-15T23:59:59.000Z" 
}

export interface Note {
  id: string;
  course: string;
  title: string;
  content: string;
  link?: string;
  createdAt: string; // This is generated by the backend
  userId: string;
}

export interface Course {
  id: string;         // UUID
  userId: string;     // Foreign key referencing User.id
  title: string;
  // instructor?: string; // Optional, as per original project description's DB schema
  // schedule?: string;   // Optional
  createdAt: string;  // ISO 8601 date string
  // updatedAt?: string; // Optional
}