export interface Assignment {
  id: string;
  title: string;
  course: string; 
  deadline: string; // e.g., "2024-03-15T23:59:59.000Z" 
}

export interface Note {
  id: string;
  course: string;
  title: string;
  content: string;
  link?: string;
  createdAt: string; // This is generated by the backend
}